name: midas_coffee_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0-155.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  shared_preferences: ^2.1.1
  go_router: ^7.1.1
  flutter_native_splash: ^2.3.0
  get_it: ^7.6.0
  get_it_mixin: ^4.2.0
  intl: ^0.18.1
  internet_connection_checker: ^1.0.0+1
  desktop_window: ^0.4.0
  google_maps_flutter: ^2.3.0
  flutter_displaymode: ^0.6.0
  flutter_animate: ^4.1.1+1
  sized_context: ^1.0.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  flutter_gen_runner:

flutter:
  uses-material-design: true
  generate: true
